---
title: Install Quarto
description: How to install Quarto on a Linux server.
format:
  html:
    code-overflow: wrap
aliases:
  - install-quarto/
  - /resources/snippets/quarto-set-versions/
  - /resources/snippets/quarto-important-ubuntu/
---
These instructions describe how to install Quarto on a Linux server. Find all available Quarto versions on the [Quarto downloads page](https://quarto.org/docs/download/).

## <!-- vale Microsoft.Contractions = NO -->What<!-- vale Microsoft.Contractions = YES --> is Quarto<!-- vale Microsoft.HeadingPuncutation = NO -->?<!-- vale Microsoft.HeadingPuncutation = YES -->

Quarto is an open-source scientific and technical publishing system built on
Pandoc, and allows users to create dynamic content with Python, R, Julia, and
Observable. Additional information about Quarto is available at
[https://quarto.org/](https://quarto.org/).

## Specify Quarto version {#specify-quarto-version-tar}

<a id="set-version"></a>

{{< include ../_snippets/quarto-set-version.md >}}

## Download and install Quarto {#download-install-quarto-tar}

Download and install the version of Quarto specified in `QUARTO_VERSION`:

```{.bash}
sudo mkdir -p /opt/quarto/${QUARTO_VERSION}

sudo curl -o quarto.tar.gz -L \
    "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.tar.gz"

sudo tar -zxvf quarto.tar.gz \
    -C "/opt/quarto/${QUARTO_VERSION}" \
    --strip-components=1
    
sudo rm quarto.tar.gz
```

## Verify Quarto installation {#verify-quarto-installation-tar}

Verify that your Quarto installation was successful:

```{.bash}
/opt/quarto/"${QUARTO_VERSION}"/bin/quarto check
```

### (Optional) Add symlink for Quarto {#add-symlink-quarto}

*Applicable to Posit Workbench, only. Not required for Connect.*

:::{.callout-important}
This section only applies to the first installation of Quarto on a
given system. For subsequent installations, skip this section.
:::

In Posit Workbench, RStudio Pro sessions have Quarto available by default. To use Quarto in VSCode or JupyterLab, you need to either symlink or install Quarto into a location on the `PATH` for those editors.

```{.bash}
# If using the default Quarto bundled with RStudio Pro
sudo ln -s /usr/lib/rstudio-server/bin/quarto/bin/quarto /usr/local/bin/quarto

# If you have installed a non-default Quarto using the above instructions
sudo ln -s /opt/quarto/${QUARTO_VERSION}/bin/quarto /usr/local/bin/quarto
```

### (Optional) Install multiple versions of Quarto {#install-multiple-versions-of-quarto}

To install multiple versions of Quarto on the same server, repeat the [steps
above](#set-version), setting `QUARTO_VERSION` to a different version number
each time.

This:

- Places different versions of Quarto in parallel folders.
- Allows you to support multiple Quarto versions in some of Posit's
professional products.

## Additional resources

### Configuring Quarto with Connect

Installing Quarto on your system before configuring Connect to allow support for Quarto content is required. Complete the installation procedures above and then review the following sections of the Posit Connect Admin Guide:

- [Quarto](https://docs.posit.co/connect/admin/quarto/)
- [Enabling Quarto Support](https://docs.posit.co/connect/admin/quarto/#enabling-quarto-support)
